name: teatimestories
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  supabase_flutter: ^1.10.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.2.3
  paytm_allinonesdk: ^1.2.6
  url_launcher: ^6.1.10
  animations: ^2.0.8
  pay: ^1.1.0 # or the latest version
  razorpay_flutter: ^1.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true



  assets:
    - assets/images/
    - assets/fonts/
    - assets/gpay_payment_config.json